config/routes.rb
YueyueWeb::Application.routes.draw do
  namespace :event do
    resources :karaokes
  end

  resources :users

  get "home/index"
  get "home/login"
  post "home/login"
  get "home/logout"

  get "yueyue/index"

  root :to => "home#index"

end

app/models/event.rb
module Event
  def self.table_name_prefix
    'event_'
  end
end

app/models/event/karaoke.rb
class Event::Karaoke < ActiveRecord::Base
  attr_accessible :describe, :paytype, :people_number_max, :people_number_min, :per_pay, :place, :start_time, :status, :title
end

app/models/user.rb
#encoding: UTF-8
require 'digest/sha2'

class User < ActiveRecord::Base
  attr_accessible :name, :password_confirmation, :password
  attr_reader :password
  
  validates :name, :presence => {:message => "邮箱未输入"}, :uniqueness => {:message => "邮箱已被注册"}
  validates :password, :confirmation => {:message => "密码不一致"}
  validate :password_must_be_present
  validates :name, :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/,
      :message => "邮件格式不正确" }

  def User.authenticate(name, password)
    if user = find_by_name(name)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end

  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "wibble" + salt)
  end

  def password=(password)
    @password = password

    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end

  private

  def password_must_be_present
    errors.add(:password, "密码未输入") unless hashed_password.present?
  end

  def generate_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/event/karaokes_controller.rb
class Event::KaraokesController < ApplicationController
  # GET /event/karaokes
  # GET /event/karaokes.json
  def index
    @event_karaokes = Event::Karaoke.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @event_karaokes }
    end
  end

  # GET /event/karaokes/1
  # GET /event/karaokes/1.json
  def show
    @event_karaoke = Event::Karaoke.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event_karaoke }
    end
  end

  # GET /event/karaokes/new
  # GET /event/karaokes/new.json
  def new
    @event_karaoke = Event::Karaoke.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event_karaoke }
    end
  end

  # GET /event/karaokes/1/edit
  def edit
    @event_karaoke = Event::Karaoke.find(params[:id])
  end

  # POST /event/karaokes
  # POST /event/karaokes.json
  def create
    @event_karaoke = Event::Karaoke.new(params[:event_karaoke])

    respond_to do |format|
      if @event_karaoke.save
        format.html { redirect_to @event_karaoke, notice: 'Karaoke was successfully created.' }
        format.json { render json: @event_karaoke, status: :created, location: @event_karaoke }
      else
        format.html { render action: "new" }
        format.json { render json: @event_karaoke.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /event/karaokes/1
  # PUT /event/karaokes/1.json
  def update
    @event_karaoke = Event::Karaoke.find(params[:id])

    respond_to do |format|
      if @event_karaoke.update_attributes(params[:event_karaoke])
        format.html { redirect_to @event_karaoke, notice: 'Karaoke was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event_karaoke.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event/karaokes/1
  # DELETE /event/karaokes/1.json
  def destroy
    @event_karaoke = Event::Karaoke.find(params[:id])
    @event_karaoke.destroy

    respond_to do |format|
      format.html { redirect_to event_karaokes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
#encoding: UTF-8
class HomeController < ApplicationController
  def index
  end

  def login
    if request.post?
      user = User.authenticate(params[:name], params[:password])
      if user
        session[:user_id] = user.id
        redirect_url = session[:after_success_login] || home_index_path
        session[:after_success_login] = nil
        redirect_to(redirect_url)
      else
        flash[:notice] = "错误的用户名或者密码。"
      end
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to home_index_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.nickname = @user.name

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: '#{@user.name} was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: '#{@user.name} was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event/karaokes_helper.rb
module Event::KaraokesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event/karaokes/_form.html.erb
<%= form_for(@event_karaoke) do |f| %>
  <% if @event_karaoke.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_karaoke.errors.count, "error") %> prohibited this event_karaoke from being saved:</h2>

      <ul>
      <% @event_karaoke.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :place %><br />
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :paytype %><br />
    <%= f.number_field :paytype %>
  </div>
  <div class="field">
    <%= f.label :people_number_min %><br />
    <%= f.number_field :people_number_min %>
  </div>
  <div class="field">
    <%= f.label :people_number_max %><br />
    <%= f.number_field :people_number_max %>
  </div>
  <div class="field">
    <%= f.label :per_pay %><br />
    <%= f.number_field :per_pay %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :describe %><br />
    <%= f.text_area :describe %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event/karaokes/edit.html.erb
<h1>Editing event_karaoke</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_karaoke %> |
<%= link_to 'Back', event_karaokes_path %>

app/views/event/karaokes/index.html.erb
<h1>Listing event_karaokes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Place</th>
    <th>Start time</th>
    <th>Paytype</th>
    <th>People number min</th>
    <th>People number max</th>
    <th>Per pay</th>
    <th>Status</th>
    <th>Describe</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @event_karaokes.each do |event_karaoke| %>
  <tr>
    <td><%= event_karaoke.title %></td>
    <td><%= event_karaoke.place %></td>
    <td><%= event_karaoke.start_time %></td>
    <td><%= event_karaoke.paytype %></td>
    <td><%= event_karaoke.people_number_min %></td>
    <td><%= event_karaoke.people_number_max %></td>
    <td><%= event_karaoke.per_pay %></td>
    <td><%= event_karaoke.status %></td>
    <td><%= event_karaoke.describe %></td>
    <td><%= link_to 'Show', event_karaoke %></td>
    <td><%= link_to 'Edit', edit_event_karaoke_path(event_karaoke) %></td>
    <td><%= link_to 'Destroy', event_karaoke, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Karaoke', new_event_karaoke_path %>

app/views/event/karaokes/new.html.erb
<h1>New event_karaoke</h1>

<%= render 'form' %>

<%= link_to 'Back', event_karaokes_path %>

app/views/event/karaokes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event_karaoke.title %>
</p>

<p>
  <b>Place:</b>
  <%= @event_karaoke.place %>
</p>

<p>
  <b>Start time:</b>
  <%= @event_karaoke.start_time %>
</p>

<p>
  <b>Paytype:</b>
  <%= @event_karaoke.paytype %>
</p>

<p>
  <b>People number min:</b>
  <%= @event_karaoke.people_number_min %>
</p>

<p>
  <b>People number max:</b>
  <%= @event_karaoke.people_number_max %>
</p>

<p>
  <b>Per pay:</b>
  <%= @event_karaoke.per_pay %>
</p>

<p>
  <b>Status:</b>
  <%= @event_karaoke.status %>
</p>

<p>
  <b>Describe:</b>
  <%= @event_karaoke.describe %>
</p>


<%= link_to 'Edit', edit_event_karaoke_path(@event_karaoke) %> |
<%= link_to 'Back', event_karaokes_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/login.html.erb
<% if (flash[:notice]) %>
<div class="error">
	<%= flash[:notice]%>
</div>
<% end %>

<%= form_tag do %>
<div>
	<label>你的邮箱地址</label>
	<div class="item">
		<%= text_field_tag(:name) %>
	</div>
	<label>你在约约的密码</label>
	<div class="item">
		<%= password_field_tag(:password) %>
	</div>
	<div class="submit-item">
		<%= submit_tag "登录" %>
		<%= link_to '注册', :controller => "users", :action => "new" %>  
		忘记密码
	</div>
</div>
<% end %>
<div>
<%= link_to(image_tag("sina_weibo.png"), "www.sina.com") %>
</div>
<div>
<%= link_to(image_tag("qq_weibo.png"), "www.qq.com") %>
</div>

app/views/layouts/application.html.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML Basic 1.0//EN" "http://www.w3.org/TR/xhtml-basic/xhtml-basic10.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
	<link href="/stylesheets/yueyue.css" media="all" rel="stylesheet" type="text/css" />
	<title>约约360</title>
	<%= csrf_meta_tag %>
</head>

<body>
	<div class="wrapper">
		<div id="hd">
			<div class="logo"> 
							<%= image_tag "yueyue.png"%>
							深圳 | 
							<% if !session[:user_id].blank? && user = User.find(session[:user_id]) %>
							[<%= link_to user.nickname, user %>]
							<%= link_to "退出", {:controller => "/home", :action => "logout"}%>
							<% else %>
							<%= link_to "登录", {:controller => "/home", :action => "login"}%>
							<% end %>
						</div>
			<div class="nav">
				
				发起约约    | 
				约约广场
				

			</div>
		</div>

		<div id="bd">
			<%= yield %>
		</div>

		<div id="ft">
			<div>
				<a href="#hd">回顶部</a>
			</div>
			给约约网提意见
		<div>
			<%= link_to "Android客户端", "./yueyue.apk"%>
		</div>
			<div class="copyright">&copy; 2011 约约网</div>
		</div>
	</div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>错误:</h2>

      <ul>
      <% @user.errors.each do |msg| %>
        <li><%= @user.errors[msg][0] %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
  <div class="field">
    <%= f.label :name, "邮箱" %><br />
    <%= f.text_field :name, :size => 40 %>
  </div>
  <div class="field">
    <%= f.label :password, '密码' %><br />
    <%= f.password_field :password, :size => 40 %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, '确认密码' %><br />
    <%= f.password_field :password_confirmation, :size => 40 %>
  </div>
  <div class="actions">
    <%= f.submit "提交" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<% if notice %>
	<p id="notice"><%=notice%></p>
<% end %>
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Hashed password:</b>
  <%= @user.hashed_password %>
</p>

<p>
  <b>Salt:</b>
  <%= @user.salt %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>